[workspace]
members = [
  "apps/desktop",
  "crates/runtime",
  "crates/base91",
  "crates/battery",
  "crates/bintree",
  "crates/config",
  "crates/codec",
  "crates/color-funcs",
  "crates/env-bootstrap",
  "crates/filedescriptor",
  "crates/filesystem",
  "crates/frecency",
  "crates/lfucache",
  "crates/luahelper",
  "crates/logging",
  "crates/lua-bridge",
  "crates/promise",
  "crates/plugin",
  "crates/portable-pty",
  "crates/procinfo",
  "crates/procinfo-funcs",
  "crates/rangeset",
  "crates/ratelim",
  "crates/serde-funcs",
  "crates/share-data",
  "crates/spawn-funcs",
  "crates/tabout",
  "crates/termwiz",
  "crates/termwiz-funcs",
  "crates/time-funcs",
  "crates/umask",
  "crates/url-funcs",
  "crates/vtparse",
  "crates/config-derive",
  "crates/terminal-bidi",
  "crates/terminal-blob-leases",
  "crates/terminal-cell",
  "crates/terminal-char-props",
  "crates/terminal-color-types",
  "crates/dynamic",
  "crates/dynamic-derive",
  "crates/terminal-escape-parser",
  "crates/terminal-font",
  "crates/gui-subcommands",
  "crates/terminal-input-types",
  "crates/open-url",
  "crates/terminal-surface",
  "crates/terminal-emulator",
  "crates/toast-notification",
  "crates/uds",
  "crates/store",
  "crates/window",
  "crates/window-funcs",
  "vendor/terminal-deps/cairo",
  "vendor/terminal-deps/fontconfig",
  "vendor/terminal-deps/freetype",
  "vendor/terminal-deps/harfbuzz",
]
default-members = [
  "apps/desktop",
  "crates/runtime",
  "crates/store",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.93"
version = "0.1.1"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1.0"
assert_fs = "1.0.4"
async-channel = "2.3"
async-executor = "1.11"
async-io = "2.3"
async-task = "4.7"
async-trait = "0.1"
backtrace = "0.3"
base64 = { version = "0.22", default-features = false }
base91 = { path = "crates/base91" }
battery = { path = "crates/battery" }
benchmarking = "0.4"
bintree = { path = "crates/bintree" }
bitflags = "1.3"
block2 = "0.6"
bstr = "1.0"
bytemuck = { version = "1.4", features = ["derive"] }
bytes = "1.0"
cairo-rs = { version = "0.18", default-features = false }
camino = "1.0"
cassowary = "0.3"
cc = { version = "1.0", features = ["parallel"] }
cgl = "0.3"
chrono = { version = "0.4", default-features = false, features = ["unstable-locales", "serde"] }
clap = { version = "4.0", features = ["derive"] }
clap_complete = "4.4"
clap_complete_fig = "4.0"
clipboard-win = "2.2"
cocoa = "=0.25.0"
codec = { path = "crates/codec" }
color-funcs = { path = "crates/color-funcs" }
colorgrad = "0.6"
config = { path = "crates/config" }
core-foundation = "=0.10.0"
core-graphics = "=0.24.0"
core-text = "=21.0.0"
criterion = "0.5"
crossbeam = "0.8"
csscolorparser = "0.6"
deltae = "0.3"
dhat = "0.3"
dirs = "6.0.0"
dns-lookup = "2.0"
downcast-rs = "1.0"
dwrote = "0.11"
embed-resource = "1.7"
emojis = "0.6"
encoding_rs = "0.8"
enum-display-derive = "0.1"
env-bootstrap = { path = "crates/env-bootstrap" }
env_logger = "0.11"
euclid = { version = "0.22", default-features = false }
fancy-regex = { version = "0.14", default-features = false, features = [] }
fastrand = "2.0"
filedescriptor = { path = "crates/filedescriptor", version = "0.8.3" }
filenamegen = "0.2.6"
filesystem = { path = "crates/filesystem" }
finl_unicode = { version = "1.3", git = "https://github.com/wez/finl_unicode.git", branch = "no_std", default-features = false, features = ["categories", "grapheme_clusters"] }
fixed = "1.23"
fixedbitset = { version = "0.4", default-features = false }
flume = "0.11"
fnv = "1.0"
fontconfig = { path = "vendor/terminal-deps/fontconfig" }
frecency = { path = "crates/frecency" }
freetype = { path = "vendor/terminal-deps/freetype" }
futures = "0.3"
futures-lite = "2.3"
futures-util = "0.3"
gethostname = "0.5"
getrandom = "0.3.1"
git2 = { version = "0.20", default-features = false, features = ["https"] }
gl_generator = "0.14"
glium = { version = "0.35", default-features = false }
governor = { version = "0.5", default-features = false, features = ["std"] }
guillotiere = "0.6"
harfbuzz = { path = "vendor/terminal-deps/harfbuzz" }
heapless = "0.8"
hdrhistogram = "7.1"
hex = { version = "0.4", default-features = false }
hostname = "0.4"
human-sort = "0.2"
humansize = "2.1"
humantime = "2.1"
image = "0.25"
intrusive-collections = "0.9"
k9 = "0.12.0"
lazy_static = "1.4"
leb128 = "0.2"
lfucache = { path = "crates/lfucache" }
libc = "0.2"
libflate = "2"
libloading = "0.8"
line_drawing = "0.8"
log = "0.4"
logging = { path = "crates/logging" }
lru = "0.16"
luahelper = { path = "crates/luahelper" }
maplit = "1.0"
memmap2 = "0.9"
memmem = "0.1"
metrics = "0.23"
miniz_oxide = "0.7"
mio = "0.8"
mlua = "0.9"
lua-bridge = { path = "crates/lua-bridge" }
names = { version = "0.12", default-features = false }
nix = "0.29"
notify = "5.0.0"
ntapi = "0.4"
nucleo-matcher = "0.3"
num = "0.4"
num-derive = "0.4"
num-traits = { version = "0.2", default-features = false }
objc = "0.2"
objc2 = "0.6"
objc2-core-graphics = "0.3"
objc2-foundation = "0.3"
objc2-user-notifications = "0.3"
ordered-float = { version = "4.1", default-features = false }
parking_lot = "0.12"
passfd = "0.1.6"
percent-encoding = "2.3"
pest = "2.7"
pest_derive = "2.7"
phf = { version = "0.11", default-features = false }
phf_codegen = "0.10"
pkg-config = "0.3"
plist = "1.7"
plugin = { path = "crates/plugin" }
portable-pty = { path = "crates/portable-pty" }
predicates = "3.0"
proc-macro2 = "1.0"
procinfo = { path = "crates/procinfo" }
procinfo-funcs = { path = "crates/procinfo-funcs" }
promise = { path = "crates/promise" }
quote = "1.0.2"
rangeset = { path = "crates/rangeset" }
ratelim = { path = "crates/ratelim" }
raw-window-handle = "0.6"
rayon = "1.10"
rcgen = "0.12"
regex = "1"
resize = "0.5"
rstest = "0.21"
rusqlite = "0.32"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-funcs = { path = "crates/serde-funcs" }
serde_json = "1.0"
serde_with = { version = "2.0", features = ["chrono_0_4"] }
serde_yaml = "0.9"
serial2 = "0.2"
sha2 = "0.10"
share-data = { path = "crates/share-data" }
shared_library = "0.1"
shell-words = "1.1"
shlex = "1.1"
signal-hook = "0.3"
siphasher = "1.0.1"
smithay-client-toolkit = { version = "0.19", default-features = false }
smol = "2.0"
socket2 = "0.5"
spa = "0.3.1"
spawn-funcs = { path = "crates/spawn-funcs" }
sqlite-cache = "0.1.4"
starship-battery = "0.10"
strsim = "0.11"
syn = "1.0"
tabout = { path = "crates/tabout" }
tar = "0.4"
tempfile = "3.20"
terminfo = "0.9"
termios = "0.3"
termwiz = { path = "crates/termwiz", version = "0.24.0" }
termwiz-funcs = { path = "crates/termwiz-funcs" }
textwrap = "0.16"
thiserror = "1.0"
time-funcs = { path = "crates/time-funcs" }
tiny-skia = "0.11"
toml = "0.8"
ucd-trie = { version = "0.1", default-features = false }
uds_windows = "1.1"
umask = { path = "crates/umask" }
unicode-normalization = "0.1.24"
unicode-segmentation = "1.12"
url = "2"
url-funcs = { path = "crates/url-funcs" }
utf8parse = "0.2"
uuid = "1.13"
varbincode = "0.1"
vtparse = { path = "crates/vtparse", version = "0.7", default-features = false }
walkdir = "2"
wayland-backend = "0.3.5"
wayland-client = "0.31"
wayland-egl = "0.32"
wayland-protocols = "0.32"
wayland-protocols-plasma = { version = "0.3.6", features = ["client"] }
terminal-bidi = { path = "crates/terminal-bidi", version = "0.2.3", default-features = false }
terminal-blob-leases = { path = "crates/terminal-blob-leases", version = "0.1.1" }
terminal-cell = { path = "crates/terminal-cell" }
terminal-char-props = { path = "crates/terminal-char-props", default-features = false }
terminal-color-types = { path = "crates/terminal-color-types", version = "0.3", default-features = false }
config-derive = { path = "crates/config-derive", version = "0.1" }
dynamic = { path = "crates/dynamic", version = "0.2.1", default-features = false }
dynamic-derive = { path = "crates/dynamic-derive", version = "0.1.1" }
terminal-escape-parser = { path = "crates/terminal-escape-parser", version = "0.1.0" }
terminal-font = { path = "crates/terminal-font" }
gui-subcommands = { path = "crates/gui-subcommands" }
terminal-input-types = { path = "crates/terminal-input-types", version = "0.1", default-features = false }
open-url = { path = "crates/open-url" }
terminal-surface = { path = "crates/terminal-surface" }
terminal-emulator = { path = "crates/terminal-emulator" }
toast-notification = { path = "crates/toast-notification" }
uds = { path = "crates/uds" }
terminal-version = { path = "crates/terminal-version" }
wgpu = "25.0.2"
whoami = "1.5"
winapi = "0.3.9"
window = { path = "crates/window" }
window-funcs = { path = "crates/window-funcs" }
windows = "0.33.0"
winreg = "0.10"
x11 = "2.21"
xcb = "1.3"
xkbcommon = "0.7.0"
xml-rs = "0.8"
zbus = "4.2"
zstd = "0.11"
zvariant = "4.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[patch.crates-io]
cairo-sys-rs = { path = "vendor/terminal-deps/cairo", version = "0.18.0" }
