[package]
authors = ["Chatminal Contributors"]
name = "terminal-cell"
version = "0.1.0"
edition = "2024"
description = "Model a Cell in a Terminal display"
license = "MIT"
documentation = "https://docs.rs/terminal-cell"
keywords = ["terminal", "cell"]

[lib]
name = "terminal_cell"

[dependencies]
finl_unicode.workspace = true
image = {workspace=true, optional=true}
log = {workspace = true, optional=true}
ordered-float = {workspace = true, optional=true}
sha2 = {workspace=true, optional=true}
serde = {workspace=true, optional=true}
thiserror = {workspace=true, optional=true}
terminal-blob-leases = {workspace = true, optional=true}
terminal-char-props.workspace = true
terminal-color-types.workspace = true
terminal-escape-parser.workspace = true
dynamic.workspace = true

[features]
std = ["serde/std", "terminal-char-props/std", "terminal-color-types/std", "terminal-escape-parser/std", "dynamic/std", "finl_unicode/std"]
use_serde = ["dep:serde", "terminal-color-types/use_serde", "terminal-escape-parser/use_serde"]
use_image = ["dep:image", "dep:terminal-blob-leases", "dep:log", "dep:ordered-float", "dep:sha2", "dep:thiserror"]

[dev-dependencies]
